### ISSUE TITLE
Could you share the code that transforms ANIMAL-10N dataset to the needed structure?

### ISSUE THREAD

**Issue by ShikunLi** [yingyichen-cyy/Nested-Co-teaching#1]
Hi，thanks for your interesting work! I find the code in this repo need ANIMAL-10N images stored in folders by category,  while the original dataset is stored as bin files. Could you share the code that transforms ANIMAL-10N dataset to the needed structure?

**Comment by yingyichen-cyy** [comment]
You only need to put images belonging to the same class into the same folder. The structure of the folder should be:
```
./data/Animal10N/train/
├── 0
├── 1
├── 2
├── 3
├── 4
├── 5
├── 6
├── 7
├── 8
└── 9
```
and so as the test set.
